### PR TITLE
ARM64 Linux build support

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Review by pldin601 — APPROVED** [review]

**Review by pldin601 — CHANGES_REQUESTED** [review]
Package `gstreamer-webrtc-1.0` was not found in the pkg-config search path.

**Comment by pldin601** [comment]
Good work! 

Let's modify this thing a bit.

1. Instead of passing `arm64`/`amd64` to build/push scripts, let's determine an actual architecture and prefix images with that platform.
2. Currently, in CircleCI, AMD and ARM images have different image tags:
  - `arm64-2022-11-07T15-28-17Z`
  - `amd64-2022-11-07T15-28-00Z`
Probably, because those branches determine timestamps independently. Can we determine timestamp before launching build and provide timestamp with an argument?

**Review by pldin601 — APPROVED** [review]

**Comment by philn** [comment]
> Let's modify this thing a bit.
> 
> 1. Instead of passing `arm64`/`amd64` to build/push scripts, let's determine an actual architecture and prefix images with that platform.

Do you mean instead of passing it as command-line argument?

> 2. (optional) Currently, in CircleCI, AMD and ARM images have different image tags:
> 
> * `arm64-2022-11-07T15-28-17Z`
> * `amd64-2022-11-07T15-28-00Z`
>   Probably, because those branches determine timestamps independently. Can we determine timestamp before launching build and provide timestamp with an argument?

That would require work on CI, I'm not familiar enough with CircleCI. We'd need the workflow to specify an env var where the date would be stored, and the push script would use that env var.

**Comment by pldin601** [comment]
> Do you mean instead of passing it as command-line argument?

Exactly.

> That would require work on CI, I'm not familiar enough with CircleCI. We'd need the workflow to specify an env var where the date would be stored, and the push script would use that env var.

This thing can be skipped. Maybe we'll migrate this to our CI in GitHub actions.

**Review by pldin601 — APPROVED** [review]
👍 👍 👍

**Pull request merged**
