### PR TITLE
Install qroverlay dependencies

### PR DESCRIPTION
**Pull request by eerimoq**

### CODE REVIEW

**Comment by eerimoq** [comment]
@philn @nazar-pc  Any feedback on this?

**Comment by nazar-pc** [comment]
I no longer work at Restream, so I can't help you with merging or releasing this

**Comment by pldin601** [comment]
@philn what these deps supposed to?

**Comment by eerimoq** [comment]
The qroverlay plugin is only build if they are present.

**Review by pldin601 — APPROVED** [review]

**Comment by pldin601** [comment]
👍

**Pull request merged**
