### PR TITLE
feat: upgrade to Ubuntu 20.10

### PR DESCRIPTION
**Pull request by jxs**
Hi @nazar-pc and thanks for fulfilling https://github.com/jxs/docker-gstreamer/commit/4b74fe601bcc94de157aabf43bcf53dcfab28b28#commitcomment-43983159!
We have been since using restreamio's gstreamer container. Thing is, we now need Ubuntu 20.10, do you also have interest in upgrading to 20.10 or, can we have a 20.10 version?
thanks!

### CODE REVIEW

**Comment by nazar-pc** [comment]
I'm on the fence on this.
20.04 is an LTS distro and 20.10 only has 9 months of support.
On the other hand 20.04's stock packages become increasingly out of date.
And regardless of those new releases of GStreamer are out often enough to maintain up to date base image.

Could you share why you need 20.10 base and can't get away with 20.04?

I don't think I'm going to maintain 2 base distros, switching to newer distro is more likely if needed.

**Comment by jxs** [comment]
yeah, it's one of those situations with stock packages out of date. We use [Janus](https://github.com/meetecho/janus-gateway) and ubuntu's 20.04 stock package `janus-tools` has a bug that has been fixed on 20.10 stock version, to avoid entering the PPA mess, updating to 20.10 seemed the easiest solution

**Comment by nazar-pc** [comment]
Yeah, I think it should be fine to bump base image.
I'm on vacation this week and not going to build images on my laptop, it will melt when building WebKit or will run out of memory, whichever happens first :joy: .

Should be able to get updated images up on weekend or early next week (most likely Monday) after some testing.

**Review by nazar-pc — APPROVED** [review]

**Comment by jxs** [comment]
thanks! :raised_hands: 
>I'm on vacation this week and not going to build images on my laptop, it will melt when building WebKit or will run out of memory, whichever happens first joy .

yeah suffered similar yesterday :joy: had to disable webkit compilation to successfully build the container

**Comment by nazar-pc** [comment]
Pushed `1.18.2.1` images to Docker Hub that are based on Ubuntu 20.10

**Pull request merged**
